{
  "openapi": "3.0.0",
  "info": {
    "title": "Road to Profit",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:5000"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "tags": [
    {
      "name": "User"
    },
    {
      "name": "Forms"
    },
    {
      "name": "Forms > Alugado"
    },
    {
      "name": "Forms > Financiado"
    },
    {
      "name": "Forms > Quitado"
    },
    {
      "name": "Reports"
    },
    {
      "name": "Reports > Alugado"
    },
    {
      "name": "Reports > Financiado"
    },
    {
      "name": "Reports > Quitado"
    }
  ],
  "paths": {
    "/api/v1/users/register": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Create User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Ricardo",
                  "email": "teste@email.com",
                  "password": "123456",
                  "confirmPassword": "123456",
                  "isPremium": false
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/users/login": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Login User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "teste@email.com",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/users/update": {
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Update User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Ricardo"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/alugado": {
      "post": {
        "tags": [
          "Forms > Alugado"
        ],
        "summary": "Create Form",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "lucroEsperado": 5000,
                  "valorFranquiaSem": 754,
                  "precoCombustivel": 6.76,
                  "consumo": 14,
                  "diasTrabalhadosSem": 6,
                  "horasTrabalhadas": 10,
                  "kilometragemSem": 2000
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Forms > Alugado"
        ],
        "summary": "Get Forms",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/alugado/5": {
      "put": {
        "tags": [
          "Forms > Alugado"
        ],
        "summary": "Update Form",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "lucroEsperado": 4000,
                  "valorFranquiaSem": 564,
                  "precoCombustivel": 6,
                  "consumo": 13,
                  "diasTrabalhadosSem": 6,
                  "horasTrabalhadas": 12,
                  "kilometragemSem": 1500
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/forms/alugado/3": {
      "delete": {
        "tags": [
          "Forms > Alugado"
        ],
        "summary": "Delete Form",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/financiado": {
      "post": {
        "tags": [
          "Forms > Financiado"
        ],
        "summary": "Create Form",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "lucroEsperado": 5000,
                  "precoCombustivel": 6.35,
                  "consumo": 13.5,
                  "folgasMensal": 4,
                  "horasTrabalhadas": 9,
                  "ipva": 1450,
                  "licenciamento": 130,
                  "seguro": 350,
                  "manutencao": 500,
                  "parcelaFinanciamento": 1450,
                  "kilometragemMes": 5000
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Forms > Financiado"
        ],
        "summary": "Get Forms",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/financiado/5": {
      "put": {
        "tags": [
          "Forms > Financiado"
        ],
        "summary": "Update Forms",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "lucroEsperado": 5000,
                  "precoCombustivel": 4.56,
                  "consumo": 13.5,
                  "folgasMensal": 8,
                  "horasTrabalhadas": 8,
                  "ipva": 2800,
                  "licenciamento": 230,
                  "seguro": 350,
                  "manutencao": 500,
                  "parcelaFinanciamento": 1450,
                  "kilometragemMes": 5000
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/financiado/1": {
      "delete": {
        "tags": [
          "Forms > Financiado"
        ],
        "summary": "Delete Form",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/quitado": {
      "post": {
        "tags": [
          "Forms > Quitado"
        ],
        "summary": "Create Form",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "lucroEsperado": 6000,
                  "precoCombustivel": 6.35,
                  "consumo": 13.5,
                  "folgasMensal": 4,
                  "horasTrabalhadas": 9,
                  "ipva": 1450,
                  "licenciamento": 130,
                  "seguro": 350,
                  "manutencao": 500,
                  "kilometragemMes": 6000
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Forms > Quitado"
        ],
        "summary": "Get Forms",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/quitado/1": {
      "put": {
        "tags": [
          "Forms > Quitado"
        ],
        "summary": "Update Forms",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "lucroEsperado": 6000,
                  "precoCombustivel": 6.35,
                  "consumo": 13.5,
                  "folgasMensal": 4,
                  "horasTrabalhadas": 9,
                  "ipva": 1450,
                  "licenciamento": 250,
                  "seguro": 250,
                  "manutencao": 800,
                  "kilometragemMes": 5000
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Forms > Quitado"
        ],
        "summary": "Delete Forms",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/alugado/3/report/a": {
      "post": {
        "tags": [
          "Reports > Alugado"
        ],
        "summary": "Create Report",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/alugado/5/report/a": {
      "get": {
        "tags": [
          "Reports > Alugado"
        ],
        "summary": "Get Report",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/financiado/5/report/f": {
      "post": {
        "tags": [
          "Reports > Financiado"
        ],
        "summary": "Create Report",
        "requestBody": {
          "content": {}
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/financiado/6/report/f": {
      "get": {
        "tags": [
          "Reports > Financiado"
        ],
        "summary": "Get Report",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/quitado/2/report/q": {
      "post": {
        "tags": [
          "Reports > Quitado"
        ],
        "summary": "Create Report",
        "requestBody": {
          "content": {}
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/api/v1/forms/quitado/1/report/q": {
      "get": {
        "tags": [
          "Reports > Quitado"
        ],
        "summary": "Get Report",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/": {
      "get": {
        "tags": [
          "default"
        ],
        "summary": "New Request",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}